/**
 * P23: Agent Task Packet Renderer
 *
 * Renders AgentTaskPacket as human-readable markdown.
 * Includes authority notice: JSON is authoritative, markdown is projection.
 */

import type { AgentTaskPacket } from "./types.js";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function renderAgentTaskPacketMarkdown(packet: AgentTaskPacket): string {
  const lines: string[] = [];

  lines.push("# Agent Task Packet");
  lines.push("");
  lines.push(`> **Authority**: This markdown is a read-only projection. The JSON file (\`agent_task_packet.json\`) is the authoritative source.`);
  lines.push("");

  // Metadata
  lines.push("## Metadata");
  lines.push("");
  lines.push(`- **Packet ID**: \`${packet.packet_id}\``);
  lines.push(`- **Scenario**: \`${packet.scenario_id}\``);
  lines.push(`- **Attempt**: ${packet.attempt}`);
  lines.push(`- **Generated**: ${packet.generated_at}`);
  lines.push("");

  // Intent
  lines.push("## Intent");
  lines.push("");
  lines.push(packet.intent);
  lines.push("");

  // Scope
  lines.push("## Authorized Scope");
  lines.push("");
  lines.push("### Allowed Files");
  lines.push("");
  if (packet.scope.allowed_files.length > 0) {
    for (const f of packet.scope.allowed_files) {
      lines.push(`- \`${f}\``);
    }
  } else {
    lines.push("_No files authorized._");
  }
  lines.push("");

  if (packet.scope.required_tests.length > 0) {
    lines.push("### Required Tests");
    lines.push("");
    for (const t of packet.scope.required_tests) {
      lines.push(`- \`${t}\``);
    }
    lines.push("");
  }

  lines.push("### Forbidden Patterns");
  lines.push("");
  for (const p of packet.scope.forbidden_patterns) {
    lines.push(`- \`${p}\``);
  }
  lines.push("");

  // Stop conditions
  lines.push("## Stop Conditions");
  lines.push("");
  for (const sc of packet.stop_conditions) {
    lines.push(`- ${sc}`);
  }
  lines.push("");

  // Feedback usage
  lines.push("## Feedback Protocol");
  lines.push("");
  lines.push(`- **Expected file**: \`${packet.feedback_usage.feedback_file_expected}\``);
  lines.push(`- **Rule**: ${packet.feedback_usage.rule}`);
  lines.push("");

  if (packet.previous_feedback_ref) {
    lines.push("## Previous Feedback");
    lines.push("");
    lines.push(`Review the feedback from the previous attempt: \`${packet.previous_feedback_ref}\``);
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(`_Auto-generated by Pantheon P23. JSON is authoritative._`);
  lines.push("");

  return lines.join("\n");
}
