/**
 * P15.2 — Localized Report Renderer
 *
 * Renders blast radius reports and implementation contexts in en or zh-CN.
 * Technical IDs (node_id, file paths, symbol names) are NEVER translated.
 *
 * Used by CLI and cockpit alike.
 */

import { getTermDisplay } from "./termGlossary.js";

export type Locale = "en" | "zh-CN";

export interface BlastRadiusReportInput {
  changed_nodes: string[];
  direct: number;
  downstream: number;
  files: number;
  symbols: number;
  tests: number;
  highest_risk: "high" | "medium" | "low";
  affected_files: string[];
  affected_tests: string[];
  risk_amplifications: Array<{
    node_id: string;
    risk_level: "high" | "medium" | "low";
    kind: string;
  }>;
  critical_paths: Array<{
    nodes: string[];
    risk_level: "high" | "medium" | "low";
  }>;
}

/** Render a blast radius markdown report in the given locale. */
export function renderLocalizedReport(input: BlastRadiusReportInput, locale: Locale): string {
  const t = (id: string) => getTermDisplay(id, locale);
  const riskLabel = t(`risk_${input.highest_risk}`);

  const lines: string[] = [
    `# ${t("report_title")}\n`,
    `## ${t("report_changed_nodes")}\n`,
    ...input.changed_nodes.map(n => `- \`${n}\``),
    "",
    `## ${t("report_summary")}\n`,
    `| ${locale === "zh-CN" ? "指标" : "Metric"} | ${locale === "zh-CN" ? "数值" : "Count"} |`,
    "|---|---|",
    `| ${t("report_direct_impact")} | ${input.direct} |`,
    `| ${t("report_total_downstream")} | ${input.downstream} |`,
    `| ${t("report_affected_files")} | ${input.files} |`,
    `| ${t("report_affected_symbols")} | ${input.symbols} |`,
    `| ${t("report_affected_tests")} | ${input.tests} |`,
    `| ${t("report_highest_risk")} | **${riskLabel}** |`,
    "",
  ];

  if (input.affected_files.length > 0) {
    lines.push(`## ${t("report_affected_files")}\n`);
    input.affected_files.forEach(f => lines.push(`- \`${f}\``));
    lines.push("");
  }

  if (input.affected_tests.length > 0) {
    lines.push(`## ${t("report_affected_tests")}\n`);
    input.affected_tests.forEach(test => lines.push(`- \`${test}\``));
    lines.push("");
  }

  const highRiskAmps = input.risk_amplifications.filter(a => a.risk_level === "high");
  if (highRiskAmps.length > 0) {
    lines.push(`## ${t("report_risk_amplification")}\n`);
    highRiskAmps.forEach(a => {
      const reason = t(`reason_${a.kind}`);
      // Preserve node_id — never translate
      lines.push(`- **\`${a.node_id}\`**: ${reason}`);
    });
    lines.push("");
  }

  if (input.critical_paths.length > 0) {
    lines.push(`## ${t("report_critical_paths")}\n`);
    input.critical_paths.slice(0, 10).forEach(p => {
      const icon = p.risk_level === "high" ? "🔴" : p.risk_level === "medium" ? "🟡" : "🟢";
      // Preserve all node IDs in paths
      lines.push(`${icon} ${p.nodes.map(n => `\`${n}\``).join(" → ")}\n`);
    });
  }

  return lines.join("\n");
}

/** Render a scoped implementation context in the given locale. */
export function renderLocalizedContext(
  input: {
    affected_files: string[];
    affected_tests: string[];
    constraints: string[];
  },
  locale: Locale,
): string {
  const t = (id: string) => getTermDisplay(id, locale);
  const now = new Date().toISOString();

  const lines: string[] = [
    `# ${t("context_title")}`,
    `# Generated by Pantheon Cockpit at ${now}`,
    "",
    `## ${t("context_affected_files")}`,
    // File paths are NEVER translated
    ...input.affected_files.map(f => `- ${f}`),
    "",
    `## ${t("context_affected_tests")}`,
    // Test IDs are NEVER translated
    ...input.affected_tests.map(test => `- ${test}`),
    "",
    `## ${t("context_constraints")}`,
    // Constraints preserve technical terms
    ...input.constraints,
  ];

  return lines.join("\n");
}
