/**
 * P18: Scope Diff Validator
 *
 * Core orchestrator: classifies files, validates tests, validates human review,
 * detects reverse issue triggers, and produces a ScopeDiffReport.
 *
 * ref: P18
 */

import type { ScopedImplementationBoundaryPackage, RequiredTestsFile } from "../scopedHandoff/types.js";
import type { ScopeDiffRequest, ScopeDiffReport, ScopeDiffViolation, ScopeDiffWarning } from "./types.js";
import { classifyChangedFiles } from "./fileClassifier.js";
import { extractChangedFilesFromDiff } from "./diffParser.js";
import { validateRequiredTests } from "./testResultValidator.js";
import { validateHumanReview } from "./humanReviewValidator.js";
import { detectReverseIssueTriggers } from "./reverseIssueDetector.js";

const GENERATED_BOUNDARY_WARNING =
  "Generated boundary files should normally be regenerated through Pantheon, not hand-edited.";

export function validateScopeDiff(input: {
  scope: ScopedImplementationBoundaryPackage;
  requiredTestsFile: RequiredTestsFile;
  request: ScopeDiffRequest;
  scopeHash: string;
  requiredTestsHash: string;
}): ScopeDiffReport {
  const { scope, requiredTestsFile, request, scopeHash, requiredTestsHash } = input;
  const violations: ScopeDiffViolation[] = [];
  const warnings: ScopeDiffWarning[] = [];
  const blockingReasons: string[] = [];

  // ------------------------------------------------------------------
  // 1. Determine changed files
  // ------------------------------------------------------------------
  let changedFiles: string[];

  if (request.changed_files && request.changed_files.length > 0) {
    changedFiles = request.changed_files;

    if (request.diff_text && request.diff_text.trim().length > 0) {
      warnings.push({
        warning_id: "w_input_precedence",
        warning_type: "input_precedence_notice",
        message: "Both changed_files and diff_text provided. changed_files takes precedence; diff_text ignored.",
      });
    }
  } else if (request.diff_text && request.diff_text.trim().length > 0) {
    const parsed = extractChangedFilesFromDiff(request.diff_text);
    changedFiles = parsed.changed_files;
    for (let i = 0; i < parsed.warnings.length; i++) {
      warnings.push({
        warning_id: `w_diff_${i}`,
        warning_type: "diff_parse_partial",
        message: parsed.warnings[i],
      });
    }
  } else {
    // No input at all
    blockingReasons.push("No changed_files or diff_text provided.");
    return buildReport(scope, request, scopeHash, requiredTestsHash, "fail", [], warnings, blockingReasons, [], emptyFileSummary(), emptyTestSummary());
  }

  // ------------------------------------------------------------------
  // 2. Classify files
  // ------------------------------------------------------------------
  const classifications = classifyChangedFiles(changedFiles, scope);

  let allowedCount = 0;
  let outsideCount = 0;
  let forbiddenCount = 0;
  let protocolCount = 0;
  let generatedBoundaryCount = 0;

  for (const c of classifications) {
    if (c.is_protocol_file) {
      protocolCount++;
      violations.push({
        violation_id: `v_protocol_${c.file_path}`,
        violation_type: "protocol_file_modified",
        severity: "high",
        file_path: c.file_path,
        message: `Protocol file "${c.file_path}" must not be modified by downstream agents.`,
        required_action: "Revert changes to protocol files. They are generated by Pantheon.",
        source: { scope_id: scope.scope_id, rule: ".pantheon/** and .cursor/** always forbidden" },
      });
      blockingReasons.push(`\`${c.file_path}\` is a Pantheon protocol file and must not be modified.`);
    } else if (c.is_forbidden) {
      forbiddenCount++;
      violations.push({
        violation_id: `v_forbidden_${c.file_path}`,
        violation_type: "forbidden_file_modified",
        severity: "high",
        file_path: c.file_path,
        message: `Forbidden file "${c.file_path}" was modified (matched pattern: ${c.matched_forbidden}).`,
        required_action: "Revert changes or create a Pantheon Reverse Issue for scope expansion.",
        source: { scope_id: scope.scope_id },
      });
      blockingReasons.push(`\`${c.file_path}\` is in the forbidden files list.`);
    } else if (c.is_allowed) {
      allowedCount++;
      if (c.is_generated_boundary_file) {
        generatedBoundaryCount++;

        // Check if modification is actually permitted by allowed_operations
        const allowedEntry = scope.allowed_files.find(f => f.path === c.matched_allowed);
        const hasModifyPermission = allowedEntry?.allowed_operations.includes("modify");

        if (!hasModifyPermission && !(request.options?.allow_generated_boundary_edits)) {
          // Generated boundary file modified without modify permission → violation
          violations.push({
            violation_id: `v_gen_boundary_${c.file_path}`,
            violation_type: "generated_boundary_modified",
            severity: "medium",
            file_path: c.file_path,
            message: `Generated boundary file "${c.file_path}" was modified but allowed_operations does not include "modify". ${GENERATED_BOUNDARY_WARNING}`,
            required_action: "Regenerate through Pantheon or request scope expansion with modify permission.",
            source: { scope_id: scope.scope_id },
          });
          blockingReasons.push(`\`${c.file_path}\` is a generated boundary file modified without modify permission.`);
        } else {
          // Has modify permission but still warn about generated files
          warnings.push({
            warning_id: `w_gen_boundary_${c.file_path}`,
            warning_type: "generated_file_modified_but_allowed",
            message: `${GENERATED_BOUNDARY_WARNING} File: "${c.file_path}".`,
          });
        }
      }
    } else {
      // Outside scope
      outsideCount++;
      violations.push({
        violation_id: `v_outside_${c.file_path}`,
        violation_type: "outside_allowed_files",
        severity: "high",
        file_path: c.file_path,
        message: `File "${c.file_path}" is outside the allowed files for this scope.`,
        required_action: "Create a Pantheon Reverse Issue or expand scope through approved workflow.",
        source: { scope_id: scope.scope_id },
      });
      blockingReasons.push(`\`${c.file_path}\` is outside allowed files.`);
    }
  }

  // ------------------------------------------------------------------
  // 3. Validate required tests
  // ------------------------------------------------------------------
  const testResult = validateRequiredTests(requiredTestsFile, scope, request.test_results, request.options, scopeHash);
  violations.push(...testResult.violations);
  warnings.push(...testResult.warnings);

  for (const v of testResult.violations) {
    if (v.violation_type === "required_tests_scope_mismatch") {
      blockingReasons.push("Required tests scope_id does not match current scope.");
    } else if (v.violation_type === "required_test_missing") {
      blockingReasons.push(`Required test missing: \`${v.test_id}\`.`);
    } else if (v.violation_type === "required_test_failed") {
      blockingReasons.push(`Required test failed: \`${v.test_id}\`.`);
    }
  }

  // ------------------------------------------------------------------
  // 4. Validate human review
  // ------------------------------------------------------------------
  const reviewResult = validateHumanReview(scope, request.human_review);
  violations.push(...reviewResult.violations);
  warnings.push(...reviewResult.warnings);

  for (const v of reviewResult.violations) {
    blockingReasons.push(v.message);
  }

  // ------------------------------------------------------------------
  // 5. Detect reverse issue triggers
  // ------------------------------------------------------------------
  const fileViolations = violations.filter(v =>
    ["outside_allowed_files", "forbidden_file_modified", "protocol_file_modified", "generated_boundary_modified"].includes(v.violation_type)
  );
  const reverseIssueViolations = detectReverseIssueTriggers({
    fileClassifications: classifications,
    fileViolations,
    testViolations: testResult.violations,
    humanReviewViolations: reviewResult.violations,
    scope,
  });
  violations.push(...reverseIssueViolations);

  // ------------------------------------------------------------------
  // 6. Determine status
  // ------------------------------------------------------------------
  const hasHumanReviewMissing = violations.some(v => v.violation_type === "human_review_missing");
  const hasReverseIssue = reverseIssueViolations.length > 0;
  const hasScopeMismatch = violations.some(v => v.violation_type === "required_tests_scope_mismatch");
  const hasHighViolations = violations.some(v =>
    v.severity === "high" && v.violation_type !== "human_review_missing" && v.violation_type !== "reverse_issue_required"
  );

  let status: ScopeDiffReport["status"];
  if (hasHumanReviewMissing) status = "requires_human_review";
  else if (hasReverseIssue) status = "requires_reverse_issue";
  else if (hasScopeMismatch || hasHighViolations) status = "fail";
  else if (violations.length > 0) status = "fail";
  else status = "pass";

  // ------------------------------------------------------------------
  // 7. Generate required actions
  // ------------------------------------------------------------------
  const requiredActions: string[] = [];
  if (outsideCount > 0 || forbiddenCount > 0 || protocolCount > 0) {
    requiredActions.push("Create Pantheon reverse issue for out-of-scope files.");
  }
  const hasGenBoundaryViolation = violations.some(v => v.violation_type === "generated_boundary_modified");
  if (hasGenBoundaryViolation) {
    requiredActions.push("Regenerate generated boundary files through Pantheon or create a reverse issue for modify permission.");
  }
  if (testResult.summary.required_tests_missing > 0) {
    requiredActions.push("Run all required tests and report results.");
  }
  if (testResult.summary.required_tests_failed > 0) {
    requiredActions.push("Fix implementation to pass all required tests.");
  }
  if (hasHumanReviewMissing) {
    requiredActions.push("Provide human review with reviewer_id and rationale.");
  }

  return buildReport(
    scope, request, scopeHash, requiredTestsHash, status,
    violations, warnings, blockingReasons, requiredActions,
    { changed_files: classifications.length, allowed_files_modified: allowedCount, outside_scope_files: outsideCount, forbidden_files_modified: forbiddenCount, protocol_files_modified: protocolCount, generated_boundary_files_modified: generatedBoundaryCount },
    testResult.summary,
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function emptyFileSummary() {
  return { changed_files: 0, allowed_files_modified: 0, outside_scope_files: 0, forbidden_files_modified: 0, protocol_files_modified: 0, generated_boundary_files_modified: 0 };
}

function emptyTestSummary() {
  return { required_tests: 0, required_tests_passed: 0, required_tests_failed: 0, required_tests_missing: 0 };
}

function buildReport(
  scope: ScopedImplementationBoundaryPackage,
  request: ScopeDiffRequest,
  scopeHash: string,
  requiredTestsHash: string,
  status: ScopeDiffReport["status"],
  violations: ScopeDiffViolation[],
  warnings: ScopeDiffWarning[],
  blockingReasons: string[],
  requiredActions: string[],
  fileSummary: { changed_files: number; allowed_files_modified: number; outside_scope_files: number; forbidden_files_modified: number; protocol_files_modified: number; generated_boundary_files_modified: number },
  testSummary: { required_tests: number; required_tests_passed: number; required_tests_failed: number; required_tests_missing: number },
): ScopeDiffReport {
  return {
    generated_at: new Date().toISOString(),
    scope_id: scope.scope_id,
    status,
    source: {
      scope_path: request.scope_path,
      required_tests_path: request.required_tests_path,
      scope_hash: scopeHash,
      required_tests_hash: requiredTestsHash,
    },
    summary: {
      ...fileSummary,
      ...testSummary,
      reverse_issue_triggers: violations.filter(v => v.violation_type === "reverse_issue_required").length,
    },
    blocking_reasons: blockingReasons,
    violations,
    warnings,
    required_actions: requiredActions,
  };
}
