/**
 * Kotlin Code Generator — Deterministic code generation from handoff package
 *
 * ref: P12-001
 *
 * Input: ImplementationHandoffPackage (from handoff_package.json)
 * Output: Kotlin source files (entities, DTOs, enums, state machine validators,
 *         conflict policy mapping, conflict policy tests)
 *
 * CONSTRAINTS:
 * - Input is ONLY handoff_package.json. No access to upstream P10 artifacts.
 * - Unknown type → generation failure (no silent String fallback).
 * - All generated files include provenance header.
 * - All field names, enum values, state machine transitions are 1:1 with handoff.
 */

import type {
  ImplementationHandoffPackage,
  DataModelSpec,
  DataModelField,
  StateMachineSpec,
  ConflictPolicyEntry,
} from "../handoff/types.js";
import { createHash } from "node:crypto";

// ---------------------------------------------------------------------------
// Type Mapping
// ---------------------------------------------------------------------------

/**
 * Deterministic mapping from handoff type strings to Kotlin types.
 * If a type is not in this map, generation MUST fail.
 */
const TYPE_MAP: Record<string, string> = {
  // Primitives
  "String": "String",
  "String (UUID)": "String",
  "String (ISO-8601)": "String",
  "Int": "Int",
  "Int?": "Int?",
  "Long": "Long",
  "Boolean": "Boolean",
  "Double": "Double",

  // Collections
  "Map<String, Int>": "Map<String, Int>",
  "List<String>": "List<String>",
  "List<RemoteChange>": "List<RemoteChange>",

  // Domain types (serialized as String in Room, typed in DTOs)
  "TriageResult": "TriageResult",
  "ReportSnapshot": "ReportSnapshot",
  "OfflineReportEnvelope": "OfflineReportEnvelope",
  "ConflictPayload": "ConflictPayload",
  "VectorClock": "VectorClock",

  // State enums (stored as String in Room)
  "PendingReportState": "PendingReportState",
  "SyncOperationState": "SyncOperationState",
  "ConflictResolutionState": "ConflictResolutionState",
  "ConflictType": "ConflictType",
};

/**
 * Resolve a handoff type to Kotlin. Throws on unknown type.
 */
function resolveType(handoffType: string, nullable: boolean): string {
  const base = TYPE_MAP[handoffType];
  if (!base) {
    throw new Error(
      `[P12] Unknown type '${handoffType}' — cannot generate Kotlin. ` +
      `Add it to TYPE_MAP or fix the handoff package.`
    );
  }
  // If the type already has ?, don't double-add
  if (nullable && !base.endsWith("?")) return `${base}?`;
  return base;
}

// ---------------------------------------------------------------------------
// Name Conversion
// ---------------------------------------------------------------------------

/** snake_case → camelCase */
function toCamelCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

/** snake_case → UPPER_SNAKE_CASE */
function toUpperSnake(s: string): string {
  return s.toUpperCase();
}

// ---------------------------------------------------------------------------
// Provenance Header
// ---------------------------------------------------------------------------

function generateHeader(
  pkg: ImplementationHandoffPackage,
  fileName: string,
  pkgHash: string,
): string {
  const lines = [
    "// ═══════════════════════════════════════════════════════════════",
    `// Generated by Pantheon Phase 12 — Deterministic Kotlin Codegen`,
    `// File: ${fileName}`,
    `// Source: handoff_package.json`,
    `// Package ID: ${pkg.package_id}`,
    `// Package Hash: ${pkgHash}`,
    `// Generated: ${new Date().toISOString()}`,
    "// DO NOT EDIT MANUALLY — regenerate from handoff package.",
    "// ═══════════════════════════════════════════════════════════════",
    "",
  ];
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Enum Generation
// ---------------------------------------------------------------------------

function generateEnums(pkg: ImplementationHandoffPackage): string {
  const parts: string[] = [];

  // State machine enums
  for (const sm of pkg.state_machines) {
    parts.push(`enum class ${sm.name} {`);
    parts.push(sm.states.map(s => `    ${s}`).join(",\n"));
    parts.push("}\n");
  }

  // Contract definition enums
  for (const cd of pkg.contract_definitions) {
    if (cd.enum_values && cd.enum_values.length > 0) {
      // Convert term to PascalCase enum name
      const enumName = cd.term
        .split("_")
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join("");
      // Skip if already generated via state machine
      if (pkg.state_machines.some(sm => sm.name === enumName)) continue;

      parts.push(`enum class ${enumName} {`);
      parts.push(cd.enum_values.map(ev => `    ${ev.value}`).join(",\n"));
      parts.push("}\n");
    }
  }

  // ConflictPolicy enum (from matrix policies)
  const policies = new Set<string>();
  for (const cpm of pkg.conflict_policy_matrix) {
    policies.add(cpm.policy);
  }
  parts.push("enum class ConflictPolicy {");
  parts.push([...policies].map(p => `    ${p}`).join(",\n"));
  parts.push("}\n");

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Entity Generation
// ---------------------------------------------------------------------------

function generateEntity(model: DataModelSpec): string {
  const lines: string[] = [];

  // Explicit table name mapping (deterministic from handoff spec)
  const tableNameMap: Record<string, string> = {
    "PendingReportEntity": "pending_reports",
    "SyncOperationEntity": "sync_operations",
    "RetryLedgerEntry": "retry_ledger",
    "ConflictRecordEntity": "conflict_records",
    "VectorClockEntry": "vector_clock_entries",
    "AuditEventEntity": "audit_events",
  };
  const resolvedTable = tableNameMap[model.name];
  if (!resolvedTable) {
    throw new Error(`[P12] Unknown entity '${model.name}' — no table name mapping.`);
  }

  lines.push(`@Entity(tableName = "${resolvedTable}")`);
  lines.push(`data class ${model.name}(`);

  const fieldLines: string[] = [];
  for (const f of model.fields) {
    const annotations: string[] = [];
    if (f.primary_key) annotations.push("@PrimaryKey");
    if (f.indexed) annotations.push(`@ColumnInfo(name = "${f.name}", index = true)`);
    else annotations.push(`@ColumnInfo(name = "${f.name}")`);

    const ktType = resolveType(f.type, f.nullable);
    const propName = toCamelCase(f.name);
    const annStr = annotations.length > 0 ? annotations.join(" ") + " " : "";
    fieldLines.push(`    ${annStr}val ${propName}: ${ktType}`);
  }
  lines.push(fieldLines.join(",\n"));
  lines.push(")");

  // Invariants as comments
  if (model.invariants.length > 0) {
    lines.push("");
    lines.push("/*");
    lines.push(" * Invariants:");
    for (const inv of model.invariants) {
      lines.push(` *   - ${inv}`);
    }
    lines.push(" */");
  }

  return lines.join("\n");
}

function generateEntities(pkg: ImplementationHandoffPackage): string {
  const parts: string[] = ["import androidx.room.*\n"];

  const entities = pkg.data_models.filter(dm => dm.kind === "room_entity");
  for (const e of entities) {
    parts.push(generateEntity(e));
    parts.push("");
  }

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// DTO Generation
// ---------------------------------------------------------------------------

function generateDto(model: DataModelSpec): string {
  const lines: string[] = [];

  lines.push(`data class ${model.name}(`);

  const fieldLines: string[] = [];
  for (const f of model.fields) {
    const ktType = resolveType(f.type, f.nullable);
    const propName = toCamelCase(f.name);
    fieldLines.push(`    val ${propName}: ${ktType}`);
  }
  lines.push(fieldLines.join(",\n"));
  lines.push(")");

  // Invariants
  if (model.invariants.length > 0) {
    lines.push("");
    lines.push("/*");
    lines.push(" * Invariants:");
    for (const inv of model.invariants) {
      lines.push(` *   - ${inv}`);
    }
    lines.push(" */");
  }

  return lines.join("\n");
}

function generateDtos(pkg: ImplementationHandoffPackage): string {
  const parts: string[] = [];

  const dtos = pkg.data_models.filter(dm => dm.kind === "network_dto");
  for (const d of dtos) {
    parts.push(generateDto(d));
    parts.push("");
  }

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// State Machine Validator Generation
// ---------------------------------------------------------------------------

function generateStateMachineValidator(sm: StateMachineSpec): string {
  const lines: string[] = [];
  const enumName = sm.name;

  // Allowed transitions set
  lines.push(`object ${enumName}Machine {`);
  lines.push("");
  lines.push(`    private val allowedTransitions: Set<Pair<${enumName}, ${enumName}>> = setOf(`);
  for (let i = 0; i < sm.allowed_transitions.length; i++) {
    const t = sm.allowed_transitions[i];
    const comma = i < sm.allowed_transitions.length - 1 ? "," : "";
    lines.push(`        Pair(${enumName}.${t.from}, ${enumName}.${t.to})${comma}`);
  }
  lines.push("    )");
  lines.push("");

  // Forbidden transitions set
  lines.push(`    private val forbiddenTransitions: Set<Pair<${enumName}, ${enumName}>> = setOf(`);
  for (let i = 0; i < sm.forbidden_transitions.length; i++) {
    const t = sm.forbidden_transitions[i];
    const comma = i < sm.forbidden_transitions.length - 1 ? "," : "";
    lines.push(`        Pair(${enumName}.${t.from}, ${enumName}.${t.to})${comma}`);
  }
  lines.push("    )");
  lines.push("");

  // Audit-required transitions
  const auditTransitions = sm.allowed_transitions.filter(t => t.audit_event_required);
  lines.push(`    private val auditRequiredTransitions: Set<Pair<${enumName}, ${enumName}>> = setOf(`);
  for (let i = 0; i < auditTransitions.length; i++) {
    const t = auditTransitions[i];
    const comma = i < auditTransitions.length - 1 ? "," : "";
    lines.push(`        Pair(${enumName}.${t.from}, ${enumName}.${t.to})${comma}`);
  }
  lines.push("    )");
  lines.push("");

  // Validator functions
  lines.push(`    fun isAllowed(from: ${enumName}, to: ${enumName}): Boolean {`);
  lines.push("        return Pair(from, to) in allowedTransitions");
  lines.push("    }");
  lines.push("");
  lines.push(`    fun isForbidden(from: ${enumName}, to: ${enumName}): Boolean {`);
  lines.push("        return Pair(from, to) in forbiddenTransitions");
  lines.push("    }");
  lines.push("");
  lines.push(`    fun requiresAudit(from: ${enumName}, to: ${enumName}): Boolean {`);
  lines.push("        return Pair(from, to) in auditRequiredTransitions");
  lines.push("    }");
  lines.push("");
  lines.push(`    fun requireAllowedTransition(from: ${enumName}, to: ${enumName}) {`);
  lines.push(`        if (isForbidden(from, to)) {`);
  lines.push(`            throw IllegalStateException("Forbidden transition: \$from -> \$to")`);
  lines.push("        }");
  lines.push(`        if (!isAllowed(from, to)) {`);
  lines.push(`            throw IllegalStateException("Unknown transition: \$from -> \$to")`);
  lines.push("        }");
  lines.push("    }");
  lines.push("}");

  return lines.join("\n");
}

function generateStateMachines(pkg: ImplementationHandoffPackage): string {
  const parts: string[] = [];

  for (const sm of pkg.state_machines) {
    parts.push(generateStateMachineValidator(sm));
    parts.push("");
  }

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Conflict Policy Mapping Generation
// ---------------------------------------------------------------------------

function generateConflictPolicy(pkg: ImplementationHandoffPackage): string {
  const lines: string[] = [];

  lines.push("object ConflictPolicyRegistry {");
  lines.push("");
  lines.push("    /**");
  lines.push("     * Returns the conflict policy for a given field group.");
  lines.push("     * Source: handoff_package.json conflict_policy_matrix");
  lines.push("     */");
  lines.push("    fun getPolicy(fieldGroup: String): ConflictPolicy {");
  lines.push("        return when (fieldGroup) {");
  for (const cpm of pkg.conflict_policy_matrix) {
    lines.push(`            "${cpm.field_group}" -> ConflictPolicy.${cpm.policy}`);
  }
  lines.push(`            else -> throw IllegalArgumentException("Unknown field group: \$fieldGroup")`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Risk level mapping
  lines.push("    fun getRiskLevel(fieldGroup: String): String {");
  lines.push("        return when (fieldGroup) {");
  for (const cpm of pkg.conflict_policy_matrix) {
    lines.push(`            "${cpm.field_group}" -> "${cpm.risk_level}"`);
  }
  lines.push(`            else -> throw IllegalArgumentException("Unknown field group: \$fieldGroup")`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Audit required mapping
  lines.push("    fun isAuditRequired(fieldGroup: String): Boolean {");
  lines.push("        return when (fieldGroup) {");
  for (const cpm of pkg.conflict_policy_matrix) {
    lines.push(`            "${cpm.field_group}" -> ${cpm.audit_required}`);
  }
  lines.push(`            else -> throw IllegalArgumentException("Unknown field group: \$fieldGroup")`);
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // All field groups constant
  lines.push("    val allFieldGroups: List<String> = listOf(");
  lines.push(pkg.conflict_policy_matrix.map(cpm => `        "${cpm.field_group}"`).join(",\n"));
  lines.push("    )");
  lines.push("");

  // Clinical (high-risk vector_clock) field groups
  const clinicalGroups = pkg.conflict_policy_matrix
    .filter(cpm => cpm.policy === "vector_clock" && cpm.risk_level === "high")
    .map(cpm => cpm.field_group);
  lines.push("    val clinicalFieldGroups: List<String> = listOf(");
  lines.push(clinicalGroups.map(g => `        "${g}"`).join(",\n"));
  lines.push("    )");
  lines.push("");

  // LWW-allowed field groups
  const lwwGroups = pkg.conflict_policy_matrix
    .filter(cpm => cpm.policy === "last_writer_wins")
    .map(cpm => cpm.field_group);
  lines.push("    val lwwFieldGroups: List<String> = listOf(");
  lines.push(lwwGroups.map(g => `        "${g}"`).join(",\n"));
  lines.push("    )");

  lines.push("}");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Conflict Policy Test Generation
// ---------------------------------------------------------------------------

function generateConflictPolicyTests(pkg: ImplementationHandoffPackage): string {
  const lines: string[] = [];

  lines.push("import org.junit.Test");
  lines.push("import kotlin.test.assertEquals");
  lines.push("import kotlin.test.assertFailsWith");
  lines.push("");
  lines.push("class ConflictPolicyTests {");
  lines.push("");

  // Test 1: Clinical fields require vector_clock
  const clinicalGroups = pkg.conflict_policy_matrix
    .filter(cpm => cpm.policy === "vector_clock" && cpm.risk_level === "high");
  lines.push("    @Test");
  lines.push("    fun testClinicalFieldsRequireVectorClockPolicy() {");
  lines.push("        val clinicalFieldGroups = listOf(");
  lines.push(clinicalGroups.map(cpm => `            "${cpm.field_group}"`).join(",\n"));
  lines.push("        )");
  lines.push("        clinicalFieldGroups.forEach { group ->");
  lines.push("            assertEquals(ConflictPolicy.vector_clock, ConflictPolicyRegistry.getPolicy(group))");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Test 2: LWW only for low-risk metadata
  const lwwGroups = pkg.conflict_policy_matrix
    .filter(cpm => cpm.policy === "last_writer_wins");
  lines.push("    @Test");
  lines.push("    fun testLWWOnlyForLowRiskMetadata() {");
  lines.push("        val lwwFieldGroups = listOf(");
  lines.push(lwwGroups.map(cpm => `            "${cpm.field_group}"`).join(",\n"));
  lines.push("        )");
  lines.push("        lwwFieldGroups.forEach { group ->");
  lines.push("            assertEquals(ConflictPolicy.last_writer_wins, ConflictPolicyRegistry.getPolicy(group))");
  lines.push("        }");
  lines.push("        // Verify no high-risk group uses LWW");
  lines.push("        ConflictPolicyRegistry.clinicalFieldGroups.forEach { group ->");
  lines.push("            assertFailsWith<AssertionError> {");
  lines.push("                assertEquals(ConflictPolicy.last_writer_wins, ConflictPolicyRegistry.getPolicy(group))");
  lines.push("            }");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Test 3: retry_attempt_count is local_only
  const localOnlyGroups = pkg.conflict_policy_matrix
    .filter(cpm => cpm.policy === "local_only");
  lines.push("    @Test");
  lines.push("    fun testLocalOnlyFields() {");
  lines.push("        val localOnlyGroups = listOf(");
  lines.push(localOnlyGroups.map(cpm => `            "${cpm.field_group}"`).join(",\n"));
  lines.push("        )");
  lines.push("        localOnlyGroups.forEach { group ->");
  lines.push("            assertEquals(ConflictPolicy.local_only, ConflictPolicyRegistry.getPolicy(group))");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Test 4: sync_cursor is server_token
  const serverTokenGroups = pkg.conflict_policy_matrix
    .filter(cpm => cpm.policy === "server_token");
  lines.push("    @Test");
  lines.push("    fun testServerTokenFields() {");
  lines.push("        val serverTokenGroups = listOf(");
  lines.push(serverTokenGroups.map(cpm => `            "${cpm.field_group}"`).join(",\n"));
  lines.push("        )");
  lines.push("        serverTokenGroups.forEach { group ->");
  lines.push("            assertEquals(ConflictPolicy.server_token, ConflictPolicyRegistry.getPolicy(group))");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Test 5: Forbidden state transitions
  lines.push("    @Test");
  lines.push("    fun testForbiddenStateTransitions() {");
  for (const sm of pkg.state_machines) {
    lines.push(`        // ${sm.name}`);
    for (const ft of sm.forbidden_transitions) {
      lines.push(`        assertFailsWith<IllegalStateException> {`);
      lines.push(`            ${sm.name}Machine.requireAllowedTransition(${sm.name}.${ft.from}, ${sm.name}.${ft.to})`);
      lines.push(`        }`);
    }
  }
  lines.push("    }");
  lines.push("");

  // Test 6: ConflictPayload required fields
  const cpDef = pkg.contract_definitions.find(cd => cd.term === "conflict_payload");
  if (cpDef?.fields) {
    const required = cpDef.fields.filter(f => f.required);
    lines.push("    @Test");
    lines.push("    fun testConflictPayloadRequiredFields() {");
    lines.push("        val payload = ConflictPayload(");
    for (let i = 0; i < required.length; i++) {
      const f = required[i];
      const propName = toCamelCase(f.name);
      const comma = i < required.length - 1 ? "," : "";
      let defaultVal = "\"test\"";
      if (f.type.startsWith("Map")) defaultVal = "mapOf(\"a\" to 1)";
      else if (f.type.startsWith("List")) defaultVal = "listOf(\"f1\")";
      else if (f.type === "ReportSnapshot") defaultVal = "\"snapshot\"";
      else if (f.type === "VectorClock") defaultVal = "mapOf(\"a\" to 1)";
      lines.push(`            ${propName} = ${defaultVal}${comma}`);
    }
    lines.push("        )");
    for (const f of required) {
      const propName = toCamelCase(f.name);
      lines.push(`        assert(payload.${propName} != null)`);
    }
    lines.push("    }");
  }

  lines.push("}");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// P13: Interface Generation
// ---------------------------------------------------------------------------

/** Task-to-interface mapping (deterministic from handoff tasks) */
const INTERFACE_MAP: Record<string, { name: string; methods: Array<{ name: string; params: string; returnType: string; suspend: boolean; doc: string }> }> = {
  "TASK-002": {
    name: "PendingReportRepository",
    methods: [
      { name: "saveDraft", params: "report: PendingReportEntity", returnType: "Unit", suspend: true, doc: "Insert with status='draft', retry_count=0" },
      { name: "updateStatus", params: "reportId: String, from: PendingReportState, to: PendingReportState", returnType: "Unit", suspend: true, doc: "Validated against PendingReportState machine" },
      { name: "findByStatus", params: "status: PendingReportState", returnType: "List<PendingReportEntity>", suspend: true, doc: "Query by status returns correct subset" },
      { name: "findById", params: "reportId: String", returnType: "PendingReportEntity?", suspend: true, doc: "Null if not found" },
      { name: "markConflicted", params: "reportId: String, conflict: ConflictPayload", returnType: "Unit", suspend: true, doc: "Set status to conflicted, store conflict payload" },
    ],
  },
  "TASK-003": {
    name: "OfflineDecisionTreeRunner",
    methods: [
      { name: "evaluate", params: "species: String, symptoms: List<String>, urgency: String", returnType: "TriageResult", suspend: false, doc: "Deterministic: same input → same output. No network call." },
      { name: "getRuleVersion", params: "", returnType: "String", suspend: false, doc: "Current rule version for display" },
      { name: "refreshRules", params: "", returnType: "Unit", suspend: true, doc: "Refresh from network without app restart" },
    ],
  },
  "TASK-004": {
    name: "SyncQueueManager",
    methods: [
      { name: "enqueue", params: "reportId: String", returnType: "Unit", suspend: true, doc: "Add to FIFO queue" },
      { name: "processNext", params: "", returnType: "SyncOperationEntity?", suspend: true, doc: "Process next in FIFO order" },
      { name: "getQueueDepth", params: "", returnType: "Int", suspend: false, doc: "Current queue size" },
      { name: "recordAttempt", params: "reportId: String, success: Boolean, httpStatus: Int?, errorCode: String?", returnType: "Unit", suspend: true, doc: "Create RetryLedgerEntry" },
    ],
  },
  "TASK-005": {
    name: "ConflictResolver",
    methods: [
      { name: "resolve", params: "local: OfflineReportEnvelope, remote: OfflineReportEnvelope, conflictPayload: ConflictPayload", returnType: "ConflictResolutionResult", suspend: false, doc: "Apply hybrid policy: clinical→review, metadata→LWW, non-overlap→auto-merge" },
      { name: "classifyFields", params: "conflictingFields: List<String>", returnType: "Map<String, ConflictPolicy>", suspend: false, doc: "Map each field to its conflict policy from matrix" },
    ],
  },
  "TASK-006": {
    name: "ClinicReplicaClient",
    methods: [
      { name: "upload", params: "request: SyncUploadRequest", returnType: "SyncUploadResult", suspend: true, doc: "POST report to clinic backend" },
      { name: "pullChanges", params: "request: SyncChangePullRequest", returnType: "SyncChangePullResponse", suspend: true, doc: "GET changes since cursor" },
      { name: "acknowledge", params: "request: SyncAckRequest", returnType: "Unit", suspend: true, doc: "ACK successful merge" },
    ],
  },
  "TASK-007": {
    name: "AuditEventWriter",
    methods: [
      { name: "write", params: "actorId: String, actionType: String, reportId: String?, details: String?", returnType: "AuditEventEntity", suspend: true, doc: "Immutable record. Payload checksum is SHA-256." },
    ],
  },
  "TASK-010": {
    name: "ConnectivityObserver",
    methods: [
      { name: "observeConnectivity", params: "", returnType: "Boolean", suspend: false, doc: "Current connectivity state" },
      { name: "onConnectivityRestored", params: "callback: () -> Unit", returnType: "Unit", suspend: false, doc: "Register callback. Debounce rapid changes." },
    ],
  },
};

function generateInterfaces(pkg: ImplementationHandoffPackage): string {
  const lines: string[] = [];

  // ConflictResolutionResult (return type for ConflictResolver)
  lines.push("/** Result of conflict resolution */");
  lines.push("data class ConflictResolutionResult(");
  lines.push("    val resolution: ConflictResolutionState,");
  lines.push("    val mergedFields: Map<String, String>,");
  lines.push("    val requiresClinician: Boolean,");
  lines.push("    val auditEventGenerated: Boolean");
  lines.push(")\n");

  for (const task of pkg.implementation_tasks) {
    const iface = INTERFACE_MAP[task.task_id];
    if (!iface) continue;

    // Find forbidden assumptions relevant to this task
    const relevantFA = pkg.forbidden_assumptions.filter(fa =>
      fa.statement.toLowerCase().includes(iface.name.toLowerCase().replace("repository", "").replace("runner", "").replace("manager", ""))
    );

    lines.push(`/**`);
    lines.push(` * ${task.title}`);
    lines.push(` * Source: ${task.task_id}`);
    if (relevantFA.length > 0) {
      lines.push(` *`);
      lines.push(` * FORBIDDEN ASSUMPTIONS:`);
      for (const fa of relevantFA) {
        lines.push(` *   ${fa.assumption_id}: ${fa.statement.substring(0, 120)}...`);
      }
    }
    lines.push(` */`);
    lines.push(`interface ${iface.name} {`);
    for (const m of iface.methods) {
      lines.push(`    /** ${m.doc} */`);
      const susp = m.suspend ? "suspend " : "";
      lines.push(`    ${susp}fun ${m.name}(${m.params}): ${m.returnType}`);
      lines.push("");
    }
    lines.push("}\n");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// P13: Abstract Base Classes
// ---------------------------------------------------------------------------

function generateAbstractBases(pkg: ImplementationHandoffPackage): string {
  const lines: string[] = [];

  // BaseSyncWorker
  lines.push("/**");
  lines.push(" * Base class for sync workers. Provides guardrails:");
  lines.push(" * - Validates state transitions before execution");
  lines.push(" * - Enforces conflict policy at sync boundary");
  lines.push(" * - Requires audit events for conflict transitions");
  lines.push(" * - Forbids silent overwrite (FA-002)");
  lines.push(" */");
  lines.push("abstract class BaseSyncWorker(");
  lines.push("    private val repository: PendingReportRepository,");
  lines.push("    private val auditWriter: AuditEventWriter,");
  lines.push("    private val guards: PantheonGuards");
  lines.push(") {");
  lines.push("");
  lines.push("    suspend fun runSyncCycle(reportId: String): SyncUploadResult {");
  lines.push("        val report = repository.findById(reportId)");
  lines.push("            ?: throw IllegalArgumentException(\"Report not found: \\$reportId\")");
  lines.push("");
  lines.push("        // Guardrail: validate state transition");
  lines.push("        guards.requireValidTransition(\"PendingReportState\",");
  lines.push("            report.status, PendingReportState.syncing.name)");
  lines.push("");
  lines.push("        // Guardrail: audit the sync attempt");
  lines.push("        auditWriter.write(\"system\", \"sync_attempt\", reportId, null)");
  lines.push("");
  lines.push("        return executeSyncCycle(report)");
  lines.push("    }");
  lines.push("");
  lines.push("    protected abstract suspend fun executeSyncCycle(report: PendingReportEntity): SyncUploadResult");
  lines.push("}");
  lines.push("");

  // BaseConflictResolver
  lines.push("/**");
  lines.push(" * Base class for conflict resolvers. Provides guardrails:");
  lines.push(" * - Clinical fields NEVER use LWW (FA-001, FA-008)");
  lines.push(" * - Overlapping clinical fields → clinician review (FA-008)");
  lines.push(" * - Audit event for every conflict resolution (FA-006)");
  lines.push(" */");
  lines.push("abstract class BaseConflictResolver(");
  lines.push("    private val guards: PantheonGuards");
  lines.push(") : ConflictResolver {");
  lines.push("");
  lines.push("    override fun resolve(");
  lines.push("        local: OfflineReportEnvelope,");
  lines.push("        remote: OfflineReportEnvelope,");
  lines.push("        conflictPayload: ConflictPayload");
  lines.push("    ): ConflictResolutionResult {");
  lines.push("        // Guardrail: verify no clinical LWW");
  lines.push("        val fieldPolicies = classifyFields(conflictPayload.conflictingFields)");
  lines.push("        for ((field, policy) in fieldPolicies) {");
  lines.push("            guards.requireNoClinicalLww(field, policy.name)");
  lines.push("        }");
  lines.push("");
  lines.push("        // Guardrail: no silent overwrite");
  lines.push("        guards.requireNoSilentOverwrite(local.vectorClock, remote.vectorClock)");
  lines.push("");
  lines.push("        // Guardrail: non-empty conflicting fields");
  lines.push("        guards.requireNonEmptyConflictingFields(conflictPayload)");
  lines.push("");
  lines.push("        return executeResolution(local, remote, conflictPayload, fieldPolicies)");
  lines.push("    }");
  lines.push("");
  lines.push("    protected abstract fun executeResolution(");
  lines.push("        local: OfflineReportEnvelope,");
  lines.push("        remote: OfflineReportEnvelope,");
  lines.push("        conflictPayload: ConflictPayload,");
  lines.push("        fieldPolicies: Map<String, ConflictPolicy>");
  lines.push("    ): ConflictResolutionResult");
  lines.push("}");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// P13: Guard Functions
// ---------------------------------------------------------------------------

function generateGuards(pkg: ImplementationHandoffPackage): string {
  const lines: string[] = [];

  // Collect clinical field groups
  const clinicalGroups = pkg.conflict_policy_matrix
    .filter(cpm => cpm.policy === "vector_clock" && cpm.risk_level === "high")
    .map(cpm => cpm.field_group);

  lines.push("/**");
  lines.push(" * Pantheon-generated runtime guards.");
  lines.push(" * These enforce handoff invariants that implementations MUST NOT bypass.");
  lines.push(" *");
  lines.push(" * Source: handoff_package.json (forbidden_assumptions + conflict_policy_matrix + state_machines)");
  lines.push(" */");
  lines.push("object PantheonGuards {");
  lines.push("");

  // Guard 1: No clinical LWW
  lines.push("    private val clinicalFieldGroups = setOf(");
  lines.push(clinicalGroups.map(g => `        "${g}"`).join(",\n"));
  lines.push("    )");
  lines.push("");
  lines.push("    /**");
  lines.push("     * FA-001: Clinical fields must NEVER use LWW.");
  lines.push("     * Enforces: vector_clock policy for patient_case_status, vet_note_summary,");
  lines.push("     * triage_report_body, risk_level, suspected_condition.");
  lines.push("     */");
  lines.push("    fun requireNoClinicalLww(fieldGroup: String, policy: String) {");
  lines.push("        if (fieldGroup in clinicalFieldGroups && policy == \"last_writer_wins\") {");
  lines.push("            throw IllegalArgumentException(");
  lines.push("                \"FA-001 violation: Clinical field group '\\$fieldGroup' must not use LWW. \" +");
  lines.push("                \"Required policy: vector_clock\"");
  lines.push("            )");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Guard 2: Valid state transition
  lines.push("    /**");
  lines.push("     * FA-005: No invented states or transitions outside defined state machines.");
  lines.push("     */");
  lines.push("    fun requireValidTransition(machineName: String, from: String, to: String) {");
  lines.push("        val machine = when (machineName) {");
  lines.push("            \"PendingReportState\" -> PendingReportStateMachine");
  lines.push("            \"SyncOperationState\" -> SyncOperationStateMachine");
  lines.push("            \"ConflictResolutionState\" -> ConflictResolutionStateMachine");
  lines.push("            else -> throw IllegalArgumentException(\"Unknown state machine: \\$machineName\")");
  lines.push("        }");
  lines.push("        // Delegate to machine's requireAllowedTransition via enum lookup");
  lines.push("        when (machineName) {");

  for (const sm of pkg.state_machines) {
    lines.push(`            "${sm.name}" -> ${sm.name}Machine.requireAllowedTransition(`);
    lines.push(`                ${sm.name}.valueOf(from), ${sm.name}.valueOf(to))`);
  }
  lines.push("            else -> {}");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Guard 3: Audit for conflict
  lines.push("    /**");
  lines.push("     * FA-006: Every conflict detection/resolution must generate audit event.");
  lines.push("     */");
  lines.push("    fun requireAuditForConflict(auditGenerated: Boolean, conflictId: String) {");
  lines.push("        if (!auditGenerated) {");
  lines.push("            throw IllegalStateException(");
  lines.push("                \"FA-006 violation: Conflict '\\$conflictId' resolved without audit event.\"");
  lines.push("            )");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Guard 4: No silent overwrite
  lines.push("    /**");
  lines.push("     * FA-002: Do not silently overwrite remote edits.");
  lines.push("     * If clocks diverge, conflict resolution is required.");
  lines.push("     */");
  lines.push("    fun requireNoSilentOverwrite(localClock: Map<String, Int>, remoteClock: Map<String, Int>) {");
  lines.push("        val diverged = localClock.any { (actor, seq) -> remoteClock[actor] != null && remoteClock[actor] != seq }");
  lines.push("        if (diverged) {");
  lines.push("            // Clocks diverge — caller must go through conflict resolution, not direct overwrite");
  lines.push("            // This guard does not throw; it is an assertion the caller checks before writing");
  lines.push("        }");
  lines.push("    }");
  lines.push("");

  // Guard 5: Non-empty conflicting fields
  lines.push("    /**");
  lines.push("     * ConflictPayload.conflicting_fields must not be empty.");
  lines.push("     */");
  lines.push("    fun requireNonEmptyConflictingFields(payload: ConflictPayload) {");
  lines.push("        if (payload.conflictingFields.isEmpty()) {");
  lines.push("            throw IllegalArgumentException(");
  lines.push("                \"ConflictPayload.conflicting_fields must not be empty for report '\\${payload.reportId}'\"");
  lines.push("            )");
  lines.push("        }");
  lines.push("    }");

  lines.push("}");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// P13: Retry/Backoff Policy Table
// ---------------------------------------------------------------------------

function generateRetryPolicy(pkg: ImplementationHandoffPackage): string {
  const lines: string[] = [];

  lines.push("/**");
  lines.push(" * Deterministic retry/backoff policy derived from handoff.");
  lines.push(" * Source: TASK-004 acceptance criteria + state_machines");
  lines.push(" */");
  lines.push("object RetryBackoffPolicy {");
  lines.push("    const val INITIAL_DELAY_MS: Long = 1000");
  lines.push("    const val BACKOFF_MULTIPLIER: Double = 2.0");
  lines.push("    const val MAX_RETRIES: Int = 5");
  lines.push("    const val MAX_DELAY_MS: Long = 60000");
  lines.push("");
  lines.push("    /**");
  lines.push("     * Calculate next retry delay using exponential backoff.");
  lines.push("     * Doubles on each failure, capped at MAX_DELAY_MS.");
  lines.push("     */");
  lines.push("    fun nextDelay(attemptNumber: Int): Long {");
  lines.push("        if (attemptNumber >= MAX_RETRIES) return -1 // Terminal");
  lines.push("        val delay = (INITIAL_DELAY_MS * Math.pow(BACKOFF_MULTIPLIER, attemptNumber.toDouble())).toLong()");
  lines.push("        return minOf(delay, MAX_DELAY_MS)");
  lines.push("    }");
  lines.push("");
  lines.push("    /**");
  lines.push("     * Should this report transition to failed_terminal?");
  lines.push("     */");
  lines.push("    fun isTerminal(attemptNumber: Int): Boolean = attemptNumber >= MAX_RETRIES");
  lines.push("}");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// P13: Abstract Contract Tests
// ---------------------------------------------------------------------------

function generateContractTests(pkg: ImplementationHandoffPackage): string {
  const lines: string[] = [];

  lines.push("import org.junit.Test");
  lines.push("import kotlin.test.assertEquals");
  lines.push("import kotlin.test.assertNotNull");
  lines.push("import kotlin.test.assertFailsWith");
  lines.push("import kotlin.test.assertTrue");
  lines.push("");

  // 1. PendingReportRepositoryContractTest
  lines.push("/**");
  lines.push(" * Any PendingReportRepository implementation MUST pass these tests.");
  lines.push(" * Source: TASK-002 acceptance criteria");
  lines.push(" */");
  lines.push("abstract class PendingReportRepositoryContractTest {");
  lines.push("    abstract fun createRepository(): PendingReportRepository");
  lines.push("    abstract fun createTestReport(): PendingReportEntity");
  lines.push("");
  lines.push("    @Test fun insertCreatesWithDraftStatus() {");
  lines.push("        TODO(\"Verify: saveDraft sets status=draft, retry_count=0\")");
  lines.push("    }");
  lines.push("    @Test fun statusTransitionValidated() {");
  lines.push("        TODO(\"Verify: updateStatus rejects forbidden transitions\")");
  lines.push("    }");
  lines.push("    @Test fun queryByStatusReturnsCorrectSubset() {");
  lines.push("        TODO(\"Verify: findByStatus returns only matching reports\")");
  lines.push("    }");
  lines.push("    @Test fun survivesProcessKill() {");
  lines.push("        TODO(\"Verify: reports persist in Room across process restart\")");
  lines.push("    }");
  lines.push("}");
  lines.push("");

  // 2. ConflictResolverContractTest
  lines.push("/**");
  lines.push(" * Any ConflictResolver implementation MUST pass these tests.");
  lines.push(" * Source: TASK-005 acceptance criteria + FA-001, FA-002, FA-008");
  lines.push(" */");
  lines.push("abstract class ConflictResolverContractTest {");
  lines.push("    abstract fun createResolver(): ConflictResolver");
  lines.push("");
  lines.push("    @Test fun clinicalConflictRequiresVectorClock() {");
  lines.push("        TODO(\"Verify: clinical field conflicts use vector_clock, never LWW\")");
  lines.push("    }");
  lines.push("    @Test fun lwwRejectedForClinicalFields() {");
  lines.push("        TODO(\"Verify: FA-001 — LWW on clinical fields throws\")");
  lines.push("    }");
  lines.push("    @Test fun metadataOnlyConflictsAutoResolveViaLWW() {");
  lines.push("        TODO(\"Verify: non-clinical metadata resolves automatically\")");
  lines.push("    }");
  lines.push("    @Test fun overlappingClinicalFieldsRequireClinicianReview() {");
  lines.push("        TODO(\"Verify: FA-008 — overlapping clinical → manual_review_required\")");
  lines.push("    }");
  lines.push("    @Test fun auditEventGeneratedForEveryResolution() {");
  lines.push("        TODO(\"Verify: FA-006 — audit event on every conflict detection/resolution\")");
  lines.push("    }");
  lines.push("    @Test fun conflictRecordPersisted() {");
  lines.push("        TODO(\"Verify: ConflictRecordEntity saved with both versions\")");
  lines.push("    }");
  lines.push("}");
  lines.push("");

  // 3. AuditEventWriterContractTest
  lines.push("/**");
  lines.push(" * Any AuditEventWriter implementation MUST pass these tests.");
  lines.push(" * Source: TASK-007 acceptance criteria + FA-006");
  lines.push(" */");
  lines.push("abstract class AuditEventWriterContractTest {");
  lines.push("    abstract fun createWriter(): AuditEventWriter");
  lines.push("");
  lines.push("    @Test fun eventsAreImmutable() {");
  lines.push("        TODO(\"Verify: no update/delete operations on audit events\")");
  lines.push("    }");
  lines.push("    @Test fun payloadChecksumIsSha256() {");
  lines.push("        TODO(\"Verify: payload_checksum is valid SHA-256 hex string\")");
  lines.push("    }");
  lines.push("    @Test fun actorIdAlwaysPopulated() {");
  lines.push("        TODO(\"Verify: actor_id is clinician ID or 'system'\")");
  lines.push("    }");
  lines.push("}");
  lines.push("");

  // 4. SyncQueueManagerContractTest
  lines.push("/**");
  lines.push(" * Any SyncQueueManager implementation MUST pass these tests.");
  lines.push(" * Source: TASK-004 acceptance criteria");
  lines.push(" */");
  lines.push("abstract class SyncQueueManagerContractTest {");
  lines.push("    abstract fun createManager(): SyncQueueManager");
  lines.push("");
  lines.push("    @Test fun fifoOrdering() {");
  lines.push("        TODO(\"Verify: reports processed in FIFO order\")");
  lines.push("    }");
  lines.push("    @Test fun retryLedgerCreatedPerAttempt() {");
  lines.push("        TODO(\"Verify: each sync attempt creates RetryLedgerEntry\")");
  lines.push("    }");
  lines.push("    @Test fun exponentialBackoff() {");
  lines.push("        TODO(\"Verify: delay doubles on each failure\")");
  lines.push("    }");
  lines.push("    @Test fun maxRetriesTransitionsToTerminal() {");
  lines.push("        TODO(\"Verify: exceeded retries → failed_terminal\")");
  lines.push("    }");
  lines.push("}");
  lines.push("");

  // 5. OfflineDecisionTreeContractTest
  lines.push("/**");
  lines.push(" * Any OfflineDecisionTreeRunner implementation MUST pass these tests.");
  lines.push(" * Source: TASK-003 acceptance criteria");
  lines.push(" */");
  lines.push("abstract class OfflineDecisionTreeContractTest {");
  lines.push("    abstract fun createRunner(): OfflineDecisionTreeRunner");
  lines.push("");
  lines.push("    @Test fun deterministic() {");
  lines.push("        TODO(\"Verify: same input always produces same output\")");
  lines.push("    }");
  lines.push("    @Test fun noNetworkCallDuringEvaluation() {");
  lines.push("        TODO(\"Verify: evaluate() works without network\")");
  lines.push("    }");
  lines.push("    @Test fun ruleVersionTracked() {");
  lines.push("        TODO(\"Verify: getRuleVersion() returns current version\")");
  lines.push("    }");
  lines.push("}");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// P13: TODO Stubs
// ---------------------------------------------------------------------------

function generateTodoStubs(pkg: ImplementationHandoffPackage): string {
  const lines: string[] = [];

  const stubTasks = pkg.implementation_tasks.filter(t =>
    ["TASK-002", "TASK-003", "TASK-004", "TASK-005", "TASK-006", "TASK-007"].includes(t.task_id)
  );

  for (const task of stubTasks) {
    const iface = INTERFACE_MAP[task.task_id];
    if (!iface) continue;

    lines.push(`/**`);
    lines.push(` * TODO stub for ${task.title}`);
    lines.push(` * Source: ${task.task_id}`);
    lines.push(` */`);
    lines.push(`class Todo${iface.name} : ${iface.name} {`);

    for (const m of iface.methods) {
      const susp = m.suspend ? "suspend " : "";
      lines.push(`    override ${susp}fun ${m.name}(${m.params}): ${m.returnType} {`);

      // Build acceptance criteria string
      const criteria = task.acceptance_criteria.map(c => `     *   - ${c}`).join("\n");
      lines.push(`        TODO(`);
      lines.push(`            """`);
      lines.push(`            Implement: ${task.title}`);
      lines.push(`            Source: ${task.task_id}`);
      lines.push(`            `);
      lines.push(`            Acceptance criteria:`);
      for (const c of task.acceptance_criteria) {
        lines.push(`              - ${c}`);
      }
      lines.push(`            """.trimIndent()`);
      lines.push(`        )`);
      lines.push(`    }`);
      lines.push("");
    }

    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type KotlinGeneratorOutput = {
  files: Array<{
    fileName: string;
    content: string;
  }>;
  metrics: {
    entity_count: number;
    dto_count: number;
    enum_count: number;
    state_machine_count: number;
    conflict_policy_groups: number;
    total_fields: number;
    allowed_transitions: number;
    forbidden_transitions: number;
    // P13
    interface_count: number;
    guard_count: number;
    contract_test_count: number;
    todo_stub_count: number;
  };
  package_hash: string;
};

export function generateKotlin(
  pkg: ImplementationHandoffPackage,
): KotlinGeneratorOutput {
  // Compute package hash for provenance
  const pkgHash = createHash("sha256")
    .update(JSON.stringify(pkg))
    .digest("hex")
    .slice(0, 16);

  const header = (name: string) => generateHeader(pkg, name, pkgHash);

  // Generate all files
  const enumsContent = generateEnums(pkg);
  const entitiesContent = generateEntities(pkg);
  const dtosContent = generateDtos(pkg);
  const stateMachinesContent = generateStateMachines(pkg);
  const conflictPolicyContent = generateConflictPolicy(pkg);
  const testsContent = generateConflictPolicyTests(pkg);

  // P13: Generate contract boundary files
  const interfacesContent = generateInterfaces(pkg);
  const abstractBasesContent = generateAbstractBases(pkg);
  const guardsContent = generateGuards(pkg);
  const retryPolicyContent = generateRetryPolicy(pkg);
  const contractTestsContent = generateContractTests(pkg);
  const todoStubsContent = generateTodoStubs(pkg);

  // Contract header (read-only warning)
  const contractHeader = (name: string) =>
    generateHeader(pkg, `contracts/${name}`, pkgHash)
      + "// READ-ONLY — DO NOT EDIT. Fix the source artifact, then regenerate.\n\n";

  // Collect metrics
  const entities = pkg.data_models.filter(dm => dm.kind === "room_entity");
  const dtos = pkg.data_models.filter(dm => dm.kind === "network_dto");
  const enumCount = pkg.state_machines.length
    + pkg.contract_definitions.filter(cd =>
      cd.enum_values && cd.enum_values.length > 0
      && !pkg.state_machines.some(sm => sm.name === cd.term.split("_").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(""))
    ).length
    + 1; // ConflictPolicy enum

  const totalFields = pkg.data_models.reduce((sum, dm) => sum + dm.fields.length, 0);
  const allowedTransitions = pkg.state_machines.reduce(
    (sum, sm) => sum + sm.allowed_transitions.length, 0
  );
  const forbiddenTransitions = pkg.state_machines.reduce(
    (sum, sm) => sum + sm.forbidden_transitions.length, 0
  );

  // P13 metrics
  const interfaceCount = Object.keys(INTERFACE_MAP).length;
  const guardCount = 5; // requireNoClinicalLww, requireValidTransition, requireAuditForConflict, requireNoSilentOverwrite, requireNonEmptyConflictingFields
  const contractTestClassCount = 5;
  const todoStubCount = pkg.implementation_tasks.filter(t =>
    ["TASK-002", "TASK-003", "TASK-004", "TASK-005", "TASK-006", "TASK-007"].includes(t.task_id)
  ).length;

  return {
    files: [
      // P12: Data layer
      { fileName: "Enums.kt", content: header("Enums.kt") + enumsContent },
      { fileName: "Entities.kt", content: header("Entities.kt") + entitiesContent },
      { fileName: "Dtos.kt", content: header("Dtos.kt") + dtosContent },
      { fileName: "StateMachines.kt", content: header("StateMachines.kt") + stateMachinesContent },
      { fileName: "ConflictPolicy.kt", content: header("ConflictPolicy.kt") + conflictPolicyContent },
      { fileName: "ConflictPolicyTests.kt", content: header("ConflictPolicyTests.kt") + testsContent },
      // P13: Contract boundary layer
      { fileName: "contracts/Interfaces.kt", content: contractHeader("Interfaces.kt") + interfacesContent },
      { fileName: "contracts/AbstractBases.kt", content: contractHeader("AbstractBases.kt") + abstractBasesContent },
      { fileName: "contracts/Guards.kt", content: contractHeader("Guards.kt") + guardsContent },
      { fileName: "contracts/RetryPolicy.kt", content: contractHeader("RetryPolicy.kt") + retryPolicyContent },
      { fileName: "contracts/ContractTests.kt", content: contractHeader("ContractTests.kt") + contractTestsContent },
      { fileName: "contracts/TodoStubs.kt", content: contractHeader("TodoStubs.kt") + todoStubsContent },
    ],
    metrics: {
      entity_count: entities.length,
      dto_count: dtos.length,
      enum_count: enumCount,
      state_machine_count: pkg.state_machines.length,
      conflict_policy_groups: pkg.conflict_policy_matrix.length,
      total_fields: totalFields,
      allowed_transitions: allowedTransitions,
      forbidden_transitions: forbiddenTransitions,
      // P13 metrics
      interface_count: interfaceCount,
      guard_count: guardCount,
      contract_test_count: contractTestClassCount,
      todo_stub_count: todoStubCount,
    },
    package_hash: pkgHash,
  };
}
