/**
 * P17c: Reverse Issue Instructions Renderer
 *
 * Renders .pantheon/reverse-issue.md with structured instructions
 * for downstream agents to escalate boundary gaps.
 *
 * ref: P17
 */

import type { ScopedImplementationBoundaryPackage } from "./types.js";

/**
 * Render the reverse issue instruction document.
 */
export function renderReverseIssueInstructions(pkg: ScopedImplementationBoundaryPackage): string {
  const lines: string[] = [];

  lines.push("# Reverse Issue Instructions");
  lines.push("");
  lines.push("If implementation requires changing Pantheon-generated contracts, **do not edit generated files directly**.");
  lines.push("");
  lines.push("Create a structured reverse issue:");
  lines.push("");
  lines.push("```bash");
  lines.push('npx tsx scripts/createImplementationIssue.ts \\');
  lines.push('  --artifact "<artifact_id>" \\');
  lines.push('  --block "<block_id>" \\');
  lines.push('  --type "<issue_type>" \\');
  lines.push('  --description "Explain the contract gap" \\');
  lines.push('  --context "Explain where implementation hit the gap"');
  lines.push("```");
  lines.push("");

  lines.push("## When to Create a Reverse Issue");
  lines.push("");
  for (const ri of pkg.reverse_issue_required_if) {
    lines.push(`### ${ri.trigger_id}`);
    lines.push("");
    lines.push(`**Condition**: ${ri.condition}`);
    lines.push("");
    lines.push(`**Action**: ${ri.required_action}`);
    lines.push("");
    lines.push("```bash");
    lines.push(ri.example_command);
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(`Scope: \`${pkg.scope_id}\``);
  lines.push(`Risk level: **${pkg.summary.risk_level.toUpperCase()}**`);
  lines.push(`Human review required: ${pkg.summary.must_require_human_review ? "yes" : "no"}`);

  return lines.join("\n");
}

/**
 * Render the .pantheon/README.md
 */
export function renderPantheonReadme(): string {
  return [
    "# .pantheon",
    "",
    "This directory is generated by Pantheon.",
    "",
    "**Do not edit manually.**",
    "",
    "These files define the implementation boundary for the current scoped task.",
    "Downstream agents (Cursor, Codex, Claude Code, human) are expected to follow this boundary.",
    "",
    "If more boundary is needed, create a Reverse Issue:",
    "",
    "```bash",
    "npx tsx scripts/createImplementationIssue.ts --artifact \"<artifact_id>\" --block \"<block_id>\" --type \"...\" --description \"...\" --context \"...\"",
    "```",
    "",
    "## Files",
    "",
    "| File | Purpose |",
    "|---|---|",
    "| `scope.json` | Core protocol package |",
    "| `handoff.json` | Reference to handoff package (not a copy) |",
    "| `blast-radius.json` | Copy of source blast radius report |",
    "| `required-tests.json` | Required test obligations |",
    "| `forbidden-assumptions.md` | Human-readable forbidden assumptions |",
    "| `reverse-issue.md` | Instructions for reverse issue creation |",
    "| `README.md` | This file |",
  ].join("\n");
}

/**
 * Render .pantheon/forbidden-assumptions.md
 */
export function renderForbiddenAssumptions(pkg: ScopedImplementationBoundaryPackage): string {
  const lines: string[] = [];

  lines.push("# Forbidden Assumptions");
  lines.push("");

  if (pkg.forbidden_assumptions.length === 0) {
    lines.push("No forbidden assumptions in current scope.");
    return lines.join("\n");
  }

  lines.push("These assumptions are explicitly forbidden within this implementation scope.");
  lines.push("Violating them may cause data corruption, silent overwrites, or audit failures.");
  lines.push("");

  for (const fa of pkg.forbidden_assumptions) {
    lines.push(`## ${fa.assumption_id}`);
    lines.push("");
    lines.push(`**Statement**: ${fa.statement}`);
    lines.push("");
    lines.push(`**Reason**: ${fa.reason}`);
    lines.push("");
    if (fa.source_nodes.length > 0) {
      lines.push(`**Source**: ${fa.source_nodes.map(s => `\`${s}\``).join(", ")}`);
      lines.push("");
    }
    if (fa.enforced_by.length > 0) {
      lines.push("**Enforced by**:");
      for (const e of fa.enforced_by) {
        const label = e.file_path || e.id;
        const srcNote = e.enforcement_source === "heuristic_downstream_match"
          ? " *(heuristic)*"
          : "";
        lines.push(`- ${e.kind}: \`${label}\`${srcNote}`);
      }
      lines.push("");
    }
  }

  // Must-preserve constraints
  if (pkg.must_preserve.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("# Must Preserve Constraints");
    lines.push("");

    for (const c of pkg.must_preserve) {
      lines.push(`## ${c.constraint_id}`);
      lines.push("");
      lines.push(`**${c.statement}**`);
      lines.push("");
      lines.push(`Severity: ${c.severity.toUpperCase()}`);
      lines.push("");
      if (c.source_nodes.length > 0) {
        lines.push(`Source: ${c.source_nodes.map(s => `\`${s}\``).join(", ")}`);
        lines.push("");
      }
      if (c.enforced_by.length > 0) {
        lines.push("Enforced by:");
        for (const e of c.enforced_by) {
          const label = e.file_path || e.id;
          const srcNote = e.enforcement_source === "heuristic_downstream_match"
            ? " *(heuristic)*"
            : "";
          lines.push(`- ${e.kind}: \`${label}\`${srcNote}`);
        }
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}
